name: flutter_friends_love_demo1
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  dio: ^2.1.0  #接口请求使用的库
  flutter_spinkit: ^3.1.0 #loading样式
  flutter_easyrefresh: ^1.2.7
  provider: ^3.0.0+1
  flutter_webview_plugin: ^0.3.4
  video_player: ^0.10.1+3
  flutter_picker: ^1.1.5
  fluttertoast: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:

  - images/main_home.png
  - images/main_home_selected.png

  - images/main_meet.png
  - images/main_meet_selected.png

  - images/main_active.png
  - images/main_active_selected.png

  - images/main_me.png
  - images/main_me_selected.png

  - images/icon_add_v.png
  - images/set_image_bg.png
  - images/icon_choose.png

  - images/icon_back_white.png

